auth_enabled: false

server:
  http_listen_port: 3105
  grpc_listen_port: 9099

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
    final_sleep: 0s
  chunk_idle_period: 10m
  chunk_retain_period: 45s
  max_transfer_retries: 1

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: log_index_
        period: 48h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/app_logs/index
    cache_location: /tmp/app_logs/boltdb-cache
    cache_ttl: 48h
    shared_store: filesystem
  filesystem:
    directory: /tmp/app_logs/chunks

compactor:
  working_directory: /tmp/app_logs/compactor
  shared_store: filesystem

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 200h
  max_query_lookback: 48h