apiVersion: 1

datasources:
  - name: LogAggregator
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    uid: log_aggregator_source
    version: 1
    editable: true
  - name: MetricDataStore
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: metric_data_source
    version: 1
    editable: true